import time
n = float(input('Digite um número e será mostrada sua tabuada:'))
print('{} x 1 é igual a {}'.format(n, n * 1))
time.sleep(0.75)
print('{} x 2 é igual a {}'.format(n, n * 2))
time.sleep(0.75)
print('{} x 3 é igual a {}'.format(n, n * 3))
time.sleep(0.75)
print('{} x 4 é igual a {}'.format(n, n * 4))
time.sleep(0.75)
print('{} x 5 é igual a {}'.format(n, n * 5))
time.sleep(0.75)
print('{} x 6 é igual a {}'.format(n, n * 6))
time.sleep(0.75)
print('{} x 7 é igual a {}'.format(n, n * 7))
time.sleep(0.75)
print('{} x 8 é igual a {}'.format(n, n * 8))
time.sleep(0.75)
print('{} x 9 é igual a {}'.format(n, n * 9))
time.sleep(0.75)
print('{} x 10 é igual a {}'.format(n, n * 10))
time.sleep(10)
print('')
print('Espero que tenha ajudado :) ')
time.sleep(2)
