import time
n = int(input('Digite um número e será mostrada sua tabuada:'))
print('{}x1 é igual a {}'.format(n, n * 1))
print('{}x2 é igual a {}'.format(n, n * 2))
print('{}x3 é igual a {}'.format(n, n * 3))
print('{}x4 é igual a {}'.format(n, n * 4))
print('{}x5 é igual a {}'.format(n, n * 5))
print('{}x6 é igual a {}'.format(n, n * 6))
print('{}x7 é igual a {}'.format(n, n * 7))
print('{}x8 é igual a {}'.format(n, n * 8))
print('{}x9 é igual a {}'.format(n, n * 9))
print('{}x10 é igual a {}'.format(n, n * 10))
time.sleep(10)
print('')
print('Espero que tenha ajudado :) ')
time.sleep(2)
